FROM redis:6.2.6-bullseye

ENV PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
    GOSU_VERSION=1.12 \
    REDIS_VERSION=6.2.6 \
    REDIS_DOWNLOAD_URL=http://download.redis.io/releases/redis-6.2.6.tar.gz \
    REDIS_DOWNLOAD_SHA=5b2b8b7a50111ef395bf1c1d5be11e6e167ac018125055daa8b5c2317ae131ab
